### ISSUE TITLE
python implementation

### ISSUE THREAD

**Issue by browshanravan** [sutugin/spark-streaming-jdbc-source#3]
Does this driver work with PySpark (for python)? Sorry I'm quite new to spark streaming and I am trying to stream from a PostgreSQL db. Also there are no instructions for installation of the driver. I could't find anything in PyPI for a pip3 based install. I would be eternally grateful if the intro could have a more in depth instruction regarding how to use or step-by-step instructions etc.

p.s. ideally I would like to be able to use it with PySpark 3.0.1 using DataFrame based methods as opposed to RDD

Many thanks in advance

**Comment by sutugin** [comment]
Hi!
You can call scala code from pyspark like here https://aseigneurin.github.io/2016/09/01/spark-calling-scala-code-from-pyspark.html

**Comment by sutugin** [comment]
In order to build a jar, you must have sbt installed (https://www.scala-sbt.org/1.x/docs/Setup.html)
Clone the repository.
In the build.sbt file specify the desired version of spark(2.3 and older) :
lazy val defaultSparkVersion = " 2.3.1"
Go to the repository folder and run the command `sbt "set test in assembly: = {}" clean assembly`
target/scala-2.11/spark-streaming-jdbc-source-2.3.1_0.0.1.jar
If you run via spark-submit : `./bin/spark-submit --master local[*] --jars /fullpath/first.jar,/fullpath/second.jar /fullpath/your-program.py`
If via payspark-shell or jupiter: 
`
jars = ["/Users/andreysutugin/jars/spark-streaming-jdbc-source-2.3.1_0.0.1.jar", 
"/Users/andreysutugin/jars/sqlite-jdbc-3.34.0.jar"]
spark = (SparkSession
         .builder
         .appName("jdbc")
         .master('local[2]')
         .config("spark.jars", ",".join(jars))
         .getOrCreate())
stream = spark.readStream.format("jdbc-streaming").options(url='jdbc:sqlite:memory',
                                                 dbtable='albums',
                                                 driver='org.sqlite.JDBC',
                                                 offsetColumn='id').load()

query = stream.writeStream.outputMode("append").format("console").start()

query.awaitTermination()
`
